config:
  - management-zone-monolith: "management-zone-monolith.json"
  - management-zone-eks: "management-zone-eks.json"

management-zone-monolith:
  - name: "monolith"

management-zone-eks:
  - name: "eks"